// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/jade/jade.d.ts
declare module 'jade' {
    export function compile(template: string, options?: any): (locals?: any) => string;
    export function compileFile(path: string, options?: any): (locals?: any) => string;
    export function compileClient(template: string, options?: any): (locals?: any) => string;
    export function compileClientWithDependenciesTracked(template: string, options?: any): {
        body: (locals?: any) => string;
        dependencies: string[];
    };
    export function render(template: string, options?: any): string;
    export function renderFile(path: string, options?: any): string;
}
